### ISSUE TITLE
Support for multi-ligand SDF files

### ISSUE THREAD

**Issue by slochower** [HannesStark/EquiBind#11]
If I supply a ligand SDF file as input, the output SDF file has only the first ligand from the input. Is this to be expected? If my goal is to dock a bunch of ligands, is the best thing to provide multiple `name1_ligand.sdf` files?

**Comment by slochower** [comment]
Ah, I can actually see now in https://github.com/HannesStark/EquiBind/blob/84fbb308b744a6b31eba3cf0095230af8a4ea7a7/commons/process_mols.py#L1140-L1205 that you only return a single `mol`. In that case, consider this a feature request :)

**Comment by HannesStark** [comment]
Thanks for the idea!

**Comment by HannesStark** [comment]
This is now included thanks to @amfaber !
