### ISSUE TITLE
Potential improvement through avoiding DGL TensorDispatcher error

### ISSUE THREAD

**Issue by PatWalters** [HannesStark/EquiBind#12]
I encountered this error when running Equibind. 

/opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: libtorch_cuda.so: cannot open shared object file: No such file or directory

According to this https://discuss.dgl.ai/t/error-tensordispatcher/2468 the error impacts performance but does not impact usage.  Equibind appears to run in spite of this error.  I thought you might want to take a look.  

Ubuntu 18.04.6 LTS
Installed according to the readme with conda env create -f environment.yml

**Comment by HannesStark** [comment]
Thanks!
We are investigating this and will keep you updated in this issue.

**Comment by HannesStark** [comment]
I was able to reproduce it on one machine. With the error being thrown the training time was the same as without. I am pretty sure that this does not impact runtime here.
I am closing this issue but am happy about additional insights from anyone else!
