### ISSUE TITLE
Only ligand sdf file is generated

### ISSUE THREAD

**Issue by gezmi** [HannesStark/EquiBind#13]
Hi,

I might have not understood everything correctly, but I expected the output to be the ligand bound to the receptor. However, I only get the  ligand, and it slightly clashes with the receptor and with itself. Is this a normal prediction?

**Comment by HannesStark** [comment]
Hi,
The receptor is just the same as your input receptor and we only treat it as a rigid body.

Unfortunately, it can happen that the predicted ligand has steric clashes with the protein since the model only has a soft constraint in the loss to partially prevent this.

**Comment by octavian-ganea** [comment]
It is a good idea to fine-tune EquiBind predictions with software like SMINA which might, in some cases, be better at preventing steric clashes. See our EquiBind-S model from the paper which does exactly that.
