### ISSUE TITLE
Measure of inference quality

### ISSUE THREAD

**Issue by hmms117** [HannesStark/EquiBind#24]
Hi,

First of all, thanks for developing this method - it is really something new.

When using the `inference_from_files` mode to infer various ligand conformations on several protein targets, how does the tool report some measure of inference quality"? Do you have some measure of conformation fit to the target?
I can see `intersection_losses_untuned` being reported - can it be used?

Many thanks!

**Comment by HannesStark** [comment]
Hi!

EquiBind does (currently) not provide a confidence score or something similar to a docking score which could be used for ranking.
If the intersection loss is unusually high it would indicate that there are intersections with the receptor and the conformation is likely not the best. However, this could also be seen in a visual inspection.

**Comment by HannesStark** [comment]
_for testing EquiBind for ranking, following EquiBind, we could try to run the (slower) tools to obtain a docking score._: correct!

The coordinates of the receptor are not adjusted if that is what you are asking. The receptor is treated as a rigid body.

The receptor files also need to be provided next to the ligand files. It does not matter whether they are provided as .pdb or .sdf. I am not sure whether that answers the question. Please let me know if unclarity remains!

**Comment by hmms117** [comment]
Thanks! It makes good sense - we will try it out! :)
