### ISSUE TITLE
Can you provide the training config file for re-docking setting ?

### ISSUE THREAD

**Issue by PhungVanDuy** [HannesStark/EquiBind#26]
Hi @HannesStark 
As I know inside `config_clean` folder only contains the config file [RDKitCoords_flexible_self_docking.yml](https://github.com/HannesStark/EquiBind/blob/main/configs_clean/RDKitCoords_flexible_self_docking.yml) to training flexible self docking. Can you also provide config to train re-docking?

**Comment by HannesStark** [comment]
Jup, it is now next to the file you pointed out!
