### ISSUE TITLE
Support for multiple random rdkit confirmations for each ligand

### ISSUE THREAD

**Issue by dylanabramson33** [HannesStark/EquiBind#28]
https://github.com/HannesStark/EquiBind/blob/f11d7807e2f8e7d63abaabadde33e06b36af8fa1/datasets/pdbbind.py#L163

Hi! I was wondering if there is currently support for using multiple confirmations per ligand in the training process. In the above snippet, it looks like there is but self.conformer_id is fixed so only the first of a mols confirmations will be used. If I wanted to add support for multiple conformations could I just change self.conformer_id to be a random sample of size num_confs or would this break other things in the pipeline?

**Comment by HannesStark** [comment]
Hey!
In principle it should be possible to use multiple ligand input conformers for training which might be a good idea.
The snippet you point out was just for inference to determine the variance of our predictions based on what RDKit conformed was generated.

**Comment by dylanabramson33** [comment]
Okay got it, thank you! I figured it could maybe help alleviate the issue of ligands with higher sensitivity to initial coordinates.

**Comment by HannesStark** [comment]
Exactly! That is why I think it might be a good idea!
