### ISSUE TITLE
Corrected SDF files positions appear to be incorrect

### ISSUE THREAD

**Issue by dinsausti-vir** [HannesStark/EquiBind#30]
Hello - I am running EquiBind to calculate binding locations for a couple of hundred ligand SDF files. The process completes without errors and the outputted _corrected.sdf files look just like the original ligand SDF with modified x,y,z coordinates. However, when I plot the protein PDB and all the corrected ligands, the ligands all fall inside of the protein structure, rather than being distributed and connected to the protein strand at different locations. This clustering of the ligands at the geometric center of the protein structure does not make sense to me intuitively, so I am trying to figure out what is going on. Any thoughts on why EquiBind gives me coordinates that bulk up at the center of the protein structure?

**Comment by HannesStark** [comment]
Hi,
To me it sounds a lot like EquiBind is identifying a location as the binding pocket and clustering the ligands at that location.

**Comment by dinsausti-vir** [comment]
You may be right. I found it strange that all ligands clustered in the same pocket, but that may very well be as it is. Ill close this ticket for the time being and take another look to make sure thats the case. If anything, Ill reopen in the future. Thanks for the quick response.
