### ISSUE TITLE
Can't kekulize mol.  Unkekulized atoms

### ISSUE THREAD

**Issue by Harry4FunResearch** [HannesStark/EquiBind#31]
I got a lot of the following errors. Any idea what went wrong? Thanks.

[15:06:44] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 18
[15:06:44] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12 13 14 15 16
[15:06:44] Can't kekulize mol.  Unkekulized atoms: 40 41 42 43 44
....

**Comment by HannesStark** [comment]
That sounds to me like RDKit cannot sanitize your input molecules. Probably you will have more success in finding what causes these errors for your ligands when just googling the error. I do not know what causes RDKit to throw them

**Comment by Harry4FunResearch** [comment]
Just tried to run the demo code you provided and got the errors. I guess it was caused by the RDKit I installed?

**Comment by yufengwhy** [comment]
I met the same problem, and install psutil, but the problem remains

**Comment by K-Leoliu** [comment]
> I met the same problem, and install psutil, but the problem remains, any advices? [@HannesStark](https://github.com/HannesStark)

I had the same problem as you. May I ask if you finally solved the problem?
