### ISSUE TITLE
Scale off for results

### ISSUE THREAD

**Issue by jadolfbr** [HannesStark/EquiBind#36]
The program runs without issue, but the scale of the SDF molecule does not match the input scale/protein. 
Have you seen this before?  Is there any recourse here?  

<img width="530" alt="Screen Shot 2022-06-16 at 1 10 33 PM" src="https://user-images.githubusercontent.com/3290052/174128315-0d0aaa78-a94f-46a9-8b67-4898d479403b.png">
<img width="320" alt="Screen Shot 2022-06-16 at 1 10 16 PM" src="https://user-images.githubusercontent.com/3290052/174128332-eba8c895-efab-4c70-bd47-37548b00177f.png">

**Comment by HannesStark** [comment]
I have not encountered this before and am not sure how the issue occurs

**Comment by jadolfbr** [comment]
The odd thing is, the molecule in general is in a good docked place.  The SDF molecule is preserved as well, but the scale is off by about 12 fold.  

<img width="211" alt="Screen Shot 2022-06-16 at 1 18 32 PM" src="https://user-images.githubusercontent.com/3290052/174129411-c7d98a85-e092-4270-9d5e-8dee8ccf211e.png">

**Comment by jadolfbr** [comment]
I have now tried with Mol2 format and PDB format and I still get the same strange scale, so something is wrong with the post-processing.  They are consistently the same scale - IE C-C bonds are 6.1A.  I will see if I can share the inputs that I am using.

**Comment by HannesStark** [comment]
I can not reproduce this issue and have also not encountered it before with other people using EquiBind.
Sorry that I cannot be of further help here.

**Comment by jadolfbr** [comment]
Sounds good.  Looks like the Cuda torch version was different than system Cuda toolkit system version - 11.3 vs 11.4.  I installed 11.4 and re-running on both GPU and CPU to see if anything comes out from that.  Also working on being able to get you exact inputs to see if it can be reproduced, but that might take some time to get through.
