### ISSUE TITLE
Does current models supported multiple suggestion outputs? 

### ISSUE THREAD

**Issue by PhungVanDuy** [HannesStark/EquiBind#38]
As I know that, current models only return one output for each pair ligand-receptor. Do current models extend to support multiple suggestions binding sites output with the ranking?

**Comment by HannesStark** [comment]
Unfortunately, the current model does not provide a score for ranking.

You could retrain a model with the 'random_vec_dim' parameter set to something higher than 0. This model would then be able to produce different suggestions.
Also, you could run SMINA on top of the EquiBind pocket prediction to obtain a score and multiple suggestions.

**Comment by PhungVanDuy** [comment]
@HannesStark  Thank you for your information. 

Do you have any suggestions about the value I need to set for `random_vec_dim`?

**Comment by PhungVanDuy** [comment]
@HannesStark  I just finished the training process with `random_vec_dim = 5` but can you give me any command to run to get multiple suggestions. I ran `python inference.py --config=configs_clean/inference.yml` by replacing the path to the new model checkpoint it still got one suggestion.

**Comment by HannesStark** [comment]
You would have to run the model multiple times. Also make sure that you have a different seed everytime when you are running that in e.g. a for loop.

A for loop like that is not currently implemented

**Comment by PhungVanDuy** [comment]
@HannesStark  I already tried something like that but the result looks still similar, seems it is still the same position to bind. 
![Screen Shot 2022-06-26 at 16 30 29](https://user-images.githubusercontent.com/28798474/175808114-1639ae22-e366-4a6a-9fb5-0b86acfe2004.png)
