### ISSUE TITLE
Bad Clashes

### ISSUE THREAD

**Issue by jadolfbr** [HannesStark/EquiBind#41]
I was able to get Equibind running on GPU and CPU versions, however, I get pretty bad clashes using the default model. The models generally look like they could be plausible as a centroid, however.  Do you have any advice for how to best remove these clashes?  In the paper, you mention Equibind+S.  Is this done as two separate tasks or do you integrate it somehow? Is this generally what you would recommend, or are their options you would recommend to try, especially for bigger ligands such as this molecule (peptide at about 180 atoms including hydrogens)?

Finally, if the general recommendation is Equibind->SMINA, which it seems to be, do you have cmd-line arguments used in your benchmarking for SMINA?  I could not find a paper supplement with these arguments. 

Example of a bad clash in the ligand is below. 
<img width="391" alt="Screen Shot 2022-06-22 at 12 51 08 PM" src="https://user-images.githubusercontent.com/3290052/175093850-a9879e1d-ba94-403e-9679-6d84b9651dd7.png">

**Comment by jadolfbr** [comment]
I ran SMINA using the following, but it takes quite a while.  Did you run -minimize or -local_only for your paper?  Did you include any side chain flexibility? Did you increase exhaustiveness for your results?

`smina -r receptor.pdbqt -l ligand.pdbqt --autobox_ligand ligand.pdbqt --autobox_add 6 --exhaustiveness 16 -o native_tuned.pdbqt  --cpu 8`

**Comment by HannesStark** [comment]
Hi!
For the cmd arguments you can have a look at #15 .
Unfortunately, EquiBind's predictions can have clashes.

We used the default exhaustiveness

**Comment by jadolfbr** [comment]
Thanks! This is very helpful! Probably could put it in supplemental for the paper.  I made the autobox_add as 5 to be around what you have - though it's probably a bit bigger than defining the x/y/z box directly.
