### ISSUE TITLE
reproduction of paper results and ligand/protein prep

### ISSUE THREAD

**Issue by abazabaaa** [HannesStark/EquiBind#49]
Hi -- 

Thanks for the fantastic effort. I would like to reproduce the results you got for the structures found in figure 14, but the PDB ID's are not available in the manuscript.

I tried to reproduce the equibind pose for Imatinib in the manuscript, but after several attempts I can get nothing close to the manuscript. My suspicion is that my preparation of the PDB file to isolated ligand and protein may be different than what you are doing.

I made a modification of the Colab notebook found here:
https://twitter.com/pablitoarantes/status/1548371667600101377?s=20&t=wXP5A7Qavf7nNykJw3gFHA

My modification includes the use of reduce, so I assume there shouldn't be much difference between what you are doing and I am doing:

https://github.com/abazabaaa/colab_tutorial/blob/main/equibind_imatinib.ipynb

** I realized I put the wrong pdb id in here to test things. That being said, for the sake of clarity, the questions below would be helpful for debugging and making sure I am running your code correctly.

Questions:

1) Can you provide the PDB id's from figure 14? It would really help ensure I am setting things up correctly.

2) Can you provide the code that was used to isolate ligands and proteins from raw PDB files downloaded from the PDB? I have a feeling there may be some details in there that are important and I am missing them (I would guess you strip ions/co-factors, but I didn't see that in the paper text).

**Comment by HannesStark** [comment]
Hi!

1. unfortunately, I missed to note down the PDB ids of these examples and do not remember them.
2. We do not use any code to isolate ligands and proteins from PDB files. We download the whole PDB data at once and there the files are already separated (found on their website under download). Only if you download the data for an individual complex then all the structures are in the same pdb file.
