### ISSUE TITLE
EquiBind result analysis 

### ISSUE THREAD

**Issue by PhungVanDuy** [HannesStark/EquiBind#51]
After a successful dock pose between a certain ligand and a receptor is generated by EquiBind, will we be able to further investigate the binding site? Like, will we be able to see what specific types of interactions made between ligand and receptor? Will be the task of identification of the residue on the primary structure that makes those interactions possible.

**Comment by HannesStark** [comment]
You could investigate the results in PyMol or a similar tool. 
EquiBind itself does not generate any predictions of which interactions should be happening or something similar.
