### ISSUE TITLE
Is is possible to predict torsion angle directly from model?

### ISSUE THREAD

**Issue by lkfo415579** [HannesStark/EquiBind#52]
I reviewed the paper GeoMol which is cited in the 3.2.2 section of the paper. 
That is a model can predict torsion angle directly. But the Equibind only outputs an approximate coordinate of docked ligand, then aligning torsion angle from rdkit conformer to the predicted coords, in order to avoid the problem of incorrect docked ligand conformer (wrong bond length and bond angle).

So why don't you guys just predict the torsion angle from the Equibind model directly? is it a possible strategy?

Thanks. It is a wonderful job.

**Comment by HannesStark** [comment]
Something in that direction with a different model is a possible strategy.
Please consider checking out https://github.com/gcorso/DiffDock for a paper related to that
