### ISSUE TITLE
about dgllife version and usage

### ISSUE THREAD

**Issue by lichman0405** [HannesStark/EquiBind#64]
Hi there!
For my personal experience, dgllife requires rdkit==2018.09.3 for some molecules issue.
What is the version of dgllife requirement in this repo? or dgllife is not necessary?

**Comment by HannesStark** [comment]
Hi!

The following is a list of packages with which the repository can be run and it does not contain dgllife
`absl-py                   1.1.0                    pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
biopandas                 0.4.1                    pypi_0    pypi
biopython                 1.79                     pypi_0    pypi
blas                      1.0                         mkl
bleach                    5.0.0                    pypi_0    pypi
bottleneck                1.3.4            py37h67323c0_0
brotlipy                  0.7.0           py37h9ed2024_1003
bzip2                     1.0.8                h1de35cc_0
ca-certificates           2022.6.15            h033912b_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
cairo                     1.16.0               h691a603_2
certifi                   2022.6.15        py37hf985489_0    conda-forge
cffi                      1.15.0           py37hc55c11b_1
charset-normalizer        2.0.12                   pypi_0    pypi
cryptography              37.0.1           py37hf6deb26_0
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1                    pypi_0    pypi
dgl                       0.8.1                    py37_0    dglteam
entrypoints               0.4                      pypi_0    pypi
fastjsonschema            2.15.3                   pypi_0    pypi
fontconfig                2.13.1               ha9ee91d_0
fonttools                 4.33.3                   pypi_0    pypi
freetype                  2.11.0               hd8bbffd_0
gettext                   0.21.0               h7535e17_0
giflib                    5.2.1                haf1e3a3_0
glib                      2.69.1               h8346a28_1
google-auth               2.7.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.46.3                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
icu                       58.2                 h0a44026_3
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.11.4                   pypi_0    pypi
importlib-resources       5.8.0                    pypi_0    pypi
intel-openmp              2021.4.0          hecd8cb5_3538
ipykernel                 6.15.0                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   hca72f7f_0
jsonschema                4.6.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-console           6.4.3                    pypi_0    pypi
jupyter-core              4.10.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.4.3                    pypi_0    pypi
lcms2                     2.12                 hf1fd2bf_0
libboost                  1.73.0              hd4c2dcd_11
libcxx                    12.0.0               h2f01273_0
libffi                    3.3                  hb1e8313_2
libgfortran               3.0.1                h93005f0_2
libiconv                  1.16                 hca72f7f_2
libpng                    1.6.37               ha441bb4_0
libtiff                   4.2.0                h87d7836_0
libwebp                   1.2.2                h56c3ce4_0
libwebp-base              1.2.2                hca72f7f_0
libxml2                   2.9.14               hbf8cd5e_0
littleutils               0.2.2                    pypi_0    pypi
llvm-openmp               12.0.0               h0dcd299_1
lz4-c                     1.9.3                h23ab428_1
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.4.0           hecd8cb5_637
mkl-service               2.4.0            py37h9ed2024_0
mkl_fft                   1.3.1            py37h4ab4a9b_0
mkl_random                1.2.2            py37hb2f4e1b_0
nbclient                  0.6.4                    pypi_0    pypi
nbconvert                 6.5.0                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_2
nest-asyncio              1.5.5                    pypi_0    pypi
networkx                  2.2                      py37_1
notebook                  6.4.12                   pypi_0    pypi
numexpr                   2.8.1            py37h2e5f0a9_0
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37h3b1a694_3
oauthlib                  3.2.0                    pypi_0    pypi
ogb                       1.3.3                    pypi_0    pypi
openbabel                 3.1.1            py37h0fef594_2    conda-forge
openssl                   1.1.1p               hfe4f2af_0    conda-forge
outdated                  0.2.1                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pcre                      8.45                 h23ab428_0
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1            py37hde71d04_0
pip                       21.2.2           py37hecd8cb5_0
pixman                    0.40.0               h9ed2024_1
plotly                    5.9.0                    pypi_0    pypi
pot                       0.8.2                    pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py-boost                  1.73.0          py37hb2f4e1b_11
pyaml                     21.10.1                  pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.12.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.4              pyhd3eb1b0_0
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1            py37hecd8cb5_0
python                    3.7.13               hdfd78df_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.1           py37hecd8cb5_0
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.1.0                   pypi_0    pypi
qtconsole                 5.3.1                    pypi_0    pypi
qtpy                      2.1.0                    pypi_0    pypi
rdkit                     2020.09.1.0      py37h81f2deb_1    rdkit
readline                  8.1.2                hca72f7f_1
requests                  2.28.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3            py37h8c7af03_0
send2trash                1.8.0                    pypi_0    pypi
setuptools                61.2.0           py37hecd8cb5_0
six                       1.16.0             pyhd3eb1b0_1
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.38.3               h707629a_0
tenacity                  8.0.1                    pypi_0    pypi
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0
torch                     1.11.0                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0           py37hecd8cb5_0
traitlets                 5.3.0                    pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
updates                   0.1.7.1                  pypi_0    pypi
urllib3                   1.26.9           py37hecd8cb5_0
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.6.0                    pypi_0    pypi
xz                        5.2.5                hca72f7f_1
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.12               h4dc903c_2
zstd                      1.4.9                h322a384_0`
