### ISSUE TITLE
Problem with pdb file input

### ISSUE THREAD

**Issue by AlexExplorer1** [HannesStark/EquiBind#7]
Preprocessed pdb file as suggested in arxiv. Trying to make the prediction but got an error:

Traceback (most recent call last):
  File "inference.py", line 471, in <module>
    inference_from_files(args)
  File "inference.py", line 339, in inference_from_files
    rec, rec_coords, c_alpha_coords, n_coords, c_coords = get_receptor(rec_path, lig, cutoff=dp['chain_radius'])
  File "E:\EquiBind-main\commons\process_mols.py", line 373, in get_receptor
    c_alpha_coords = np.concatenate(valid_c_alpha_coords, axis=0)  # [n_residues, 3]
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by HannesStark** [comment]
Hi,
Are you using the data as we provide it on zenodo?

To figure out what is going on, I would recommend printing the name of the complex for which this is happening and looking at how many chains it has and how big the chain is in which this issue is occuring.

**Comment by AlexExplorer1** [comment]
Hi,
Thank you for answer!
I am using pdb files from https://www.rcsb.org/
I was trying the different proteins, but got pretty much the same error.
Here is example:
2SBL, has 2 chains and length of 839
Is any restriction for the number of  chains or length of protein?

**Comment by HannesStark** [comment]
There should be no restriction on the number of chains or the length of the protein.
What are the lengths of the chains in your example. And maybe it helps to visualize the complex to figure out what is going on. I would use PyMol for that.

**Comment by AlexExplorer1** [comment]
Thank you. I solved problem using this suggestion: https://github.com/HannesStark/EquiBind/issues/9
